Repository Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024, pull requests merged in 2024-11, with the labels that each got.

#210 se instalo dependencia lottie y se modificó la UI de las tarjetas de productos
  app/build.gradle.kts
  app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/res/layout/product_card.xml
  app/src/main/res/raw/error_animation.json
  app/src/main/res/raw/loading_animation.json
  gradle/libs.versions.toml
Labels: documentation, enhancement

#216 Jesica alvarez
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Register.java
Labels: documentation, enhancement

#218 Gustavo toscano
  app/src/main/java/com/example/tiendadecampeones/models/AccessTokenResponse.java
  app/src/main/java/com/example/tiendadecampeones/models/RefreshTokenRequest.java
  app/src/main/java/com/example/tiendadecampeones/models/UserLogInResponse.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/network/AuthInterceptor.java
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/ManageProfile.java
  app/src/main/java/com/example/tiendadecampeones/ui/PaymentMethodsActivity.java
Labels: bug, enhancement

#220 Se sube mejoras en las activiy Dashboard, AdminOrders y Order
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/AdminOrdersActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java
  app/src/main/java/com/example/tiendadecampeones/ui/OrderActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
Labels: documentation, enhancement

#219 Denisse sabeff - Agrego máximo de caracteres a campos de contraseña
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
Labels: enhancement

#217 correcion de renderizado de talle seleccionado, ajuste de diseño en l…
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement
