Repository Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024, pull requests merged in 2024-10, with the labels that each got.

#134 Se configuro la app para que se pueda usar únicamente de manera vertical
  app/src/main/AndroidManifest.xml
Labels: documentation, enhancement

#140 Se agrega animación a layout activity_main.xml
  app/build.gradle.kts
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/raw/estrellas.json
Labels: documentation, enhancement

#141 Cristian recabarren - Actividades de Inicio de app, login/registro y home
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/MainActivity.java
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
Labels: documentation, working on

#142 Funcionalidad de Carro (agregar, disminuir y eliminar productos)
  app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/Product.java
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
  app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/cart_item.xml
  app/src/main/res/raw/lineas.json
Labels: documentation, enhancement

#143 Agrego dependencias para retrofit y modelos para pedidos, usuarios, y…
  app/build.gradle.kts
  app/src/main/java/com/example/tiendadecampeones/models/Detalle.java
  app/src/main/java/com/example/tiendadecampeones/models/FormaDePago.java
  app/src/main/java/com/example/tiendadecampeones/models/Pedido.java
  app/src/main/java/com/example/tiendadecampeones/models/Producto.java
  app/src/main/java/com/example/tiendadecampeones/models/UserLogInResponse.java
  app/src/main/java/com/example/tiendadecampeones/models/Usuario.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/Home.java
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
  gradle/libs.versions.toml
Labels: documentation, enhancement

#144 Subo avance en dashboard y order
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/adapters/OrderAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/DashboardOrder.java
  app/src/main/java/com/example/tiendadecampeones/models/Order.java
  app/src/main/java/com/example/tiendadecampeones/models/OrderDetail.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiInterface.java
  app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java
  app/src/main/java/com/example/tiendadecampeones/ui/Order.java
  app/src/main/java/com/example/tiendadecampeones/ui/OrderActivity.java
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_order.xml
  app/src/main/res/layout/list_item_order.xml
  app/src/main/res/menu/menu_filter.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement

#145 Cristian recabarren - activity_products.xml | activity_edit_profile.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/ui/ManageProfile.java
  app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
  app/src/main/res/drawable/no_accounts_35dp_7d1010_fill0_wght400_grad0_opsz40.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_products.xml
  app/src/main/res/layout/activity_profile.xml
Labels: documentation, enhancement, working on

#146 Comentado de código
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/models/Order.java
  app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java
  app/src/main/java/com/example/tiendadecampeones/ui/OrderActivity.java
Labels: documentation

#147 Subo correcciones en las activity Dashboard y Order
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/network/ApiInterface.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java
  app/src/main/java/com/example/tiendadecampeones/ui/OrderActivity.java
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_order.xml
Labels: documentation, enhancement

#148 Desarrollo y modificaciones en activities home, profile y products.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/ui/ManageProfile.java
  app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_products.xml
  app/src/main/res/layout/activity_profile.xml
Labels: documentation, enhancement, working on

#151 Agrego código para jwt, autorización basado en roles y activity para administrador
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/adapters/AdminOrderAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/UserLogInResponse.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/network/AuthInterceptor.java
  app/src/main/java/com/example/tiendadecampeones/network/RetrofitClient.java
  app/src/main/java/com/example/tiendadecampeones/ui/AdminOrdersActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Home.java
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
  app/src/main/res/layout/activity_admin_orders.xml
  app/src/main/res/layout/admin_orders.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement

#152 Cristian recabarren
  app/src/main/java/com/example/tiendadecampeones/ui/ManageProfile.java
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement, working on

#153 Victoria urcola
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/Size.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductCategories.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/product_card.xml
Labels: enhancement

#154 Gustavo toscano
  app/src/main/java/com/example/tiendadecampeones/models/FormaDePago.java
  app/src/main/java/com/example/tiendadecampeones/models/PaymentMethods.java
  app/src/main/java/com/example/tiendadecampeones/models/Pedido.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/PaymentMethodsActivity.java
  app/src/main/res/layout/activity_payment_method.xml
  app/src/main/res/values/colors.xml
Labels: documentation, enhancement

#155 mejoras en la logica de product e implementacion de la redireccion a …
  app/build.gradle.kts
  app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/Product.java
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
  app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductCategories.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
  app/src/main/res/drawable/error_image.png
  app/src/main/res/drawable/placeholder_image.png
  build.gradle.kts
Labels: documentation, enhancement, working on

#156 Subo avances para las activity Dashboard y Order
  app/src/main/java/com/example/tiendadecampeones/adapters/OrderAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/DashboardOrder.java
  app/src/main/java/com/example/tiendadecampeones/models/Order.java
  app/src/main/java/com/example/tiendadecampeones/models/Usuario.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/OrderActivity.java
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_order.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement

#157 Victoria urcola
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/Product.java
Labels: working on

#161 Julieta negrette-Activity edit_profile
  app/src/main/java/com/example/tiendadecampeones/models/UserProfile.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiClient.java
  app/src/main/res/layout/activity_edit_profile.xml
Labels: documentation, enhancement, working on

#165 borro linea duplicada
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
Labels: working on

#164 Cristian recabarren | activity_edit_profile.xml - ManageProfile.java - LoginActivity.java
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/ManageProfile.java
  app/src/main/java/com/example/tiendadecampeones/ui/PaymentMethodsActivity.java
Labels: documentation, enhancement, wontfix

#166 Agrego el adaptador OrderProductAdapters, mejoras en la activity Orde…
  app/src/main/java/com/example/tiendadecampeones/adapters/OrderProductAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/Order.java
  app/src/main/java/com/example/tiendadecampeones/models/OrderDetail.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java
  app/src/main/java/com/example/tiendadecampeones/ui/OrderActivity.java
  app/src/main/res/layout/activity_order.xml
  app/src/main/res/layout/item_product_order.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement

#167 Victoria urcola
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/Product.java
  app/src/main/java/com/example/tiendadecampeones/models/Size.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
Labels: working on

#168 Gustavo toscano
  app/build.gradle.kts
  app/src/main/java/com/example/tiendadecampeones/models/PaymentMethods.java
  app/src/main/java/com/example/tiendadecampeones/models/Pedido.java
  app/src/main/java/com/example/tiendadecampeones/models/Product.java
  app/src/main/java/com/example/tiendadecampeones/models/Producto.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/PaymentMethodsActivity.java
  app/src/main/res/layout/activity_payment_method.xml
Labels: documentation, enhancement

#169 Hago funcional metodo cancelar pedido
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/OrderActivity.java
Labels: documentation, enhancement

#171 Agrego mejoras en Order Adapter y en activity Order
  .settings/org.eclipse.buildship.core.prefs
  app/src/main/java/com/example/tiendadecampeones/adapters/OrderAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/Order.java
  app/src/main/java/com/example/tiendadecampeones/ui/OrderActivity.java
Labels: documentation, enhancement

#172 elimino archivo de .settings
  .settings/org.eclipse.buildship.core.prefs
Labels: documentation, enhancement

#173 Jesica alvarez- Se trabajo en el carro
  app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
  app/src/main/java/com/example/tiendadecampeones/ui/UpdateTotalListener.java
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/cart_item.xml
Labels: documentation, enhancement, working on

#175 Subo mejoras en la activity order
  app/src/main/res/layout/activity_order.xml
Labels: documentation, enhancement

#176 Agrego mejoras en la lógica de la activity edit_profile
  app/src/main/java/com/example/tiendadecampeones/models/UserProfile.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiClient.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/ManageProfile.java
Labels: documentation, enhancement

#177 Denisse Sabeff - Activity administrador
  app/src/main/java/com/example/tiendadecampeones/ui/AdminOrdersActivity.java
  app/src/main/res/layout/activity_admin_orders.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement

#178 implementacion de funcionalidad usando sharedpreference para persistir productos en el cart
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java
  app/src/main/java/com/example/tiendadecampeones/adapters/CartResumeAdapter.java
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/Product.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java
  app/src/main/java/com/example/tiendadecampeones/utils/SharedPrefManager.java
Labels: documentation, enhancement, working on

#179 finalizacion del logout
  app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
Labels: documentation, enhancement

#180 Cristian recabarren
  app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/Product.java
  app/src/main/java/com/example/tiendadecampeones/models/Size.java
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
  app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/UpdateTotalListener.java
Labels: documentation, enhancement, working on

#181 Ajusté renderizado de productos agregados en el carro
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
Labels: documentation, enhancement, working on

#182 Se soluciono modificacion de la modificacion del perfil
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/ManageProfile.java
  app/src/main/java/com/example/tiendadecampeones/ui/PaymentMethodsActivity.java
Labels: bug

#183 Subo mejoras en las activity Order y Admin Order
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/adapters/OrderProductAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/Order.java
  app/src/main/java/com/example/tiendadecampeones/ui/AdminOrdersActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/OrderActivity.java
  app/src/main/res/layout/activity_admin_orders.xml
  app/src/main/res/layout/activity_order.xml
  app/src/main/res/layout/item_product_order.xml
Labels: documentation, enhancement

#184 Subo AdminOrderAdapter y mejoras en la activity Admin Orders
  app/src/main/java/com/example/tiendadecampeones/adapters/AdminOrderAdapter.java
  app/src/main/java/com/example/tiendadecampeones/ui/AdminOrdersActivity.java
  app/src/main/res/layout/admin_orders.xml
Labels: documentation, enhancement

#185 Carro de compras, sección de productos y navegación en general
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/Pedido.java
  app/src/main/java/com/example/tiendadecampeones/models/Product.java
  app/src/main/java/com/example/tiendadecampeones/ui/AboutUs.java
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
  app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java
  app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java
  app/src/main/java/com/example/tiendadecampeones/ui/Home.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_product_categories.xml
  app/src/main/res/layout/cart_item.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement, working on

#186 Agrego desarrollo de funcionalidades en el Carro de compras
  app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java
  app/src/main/java/com/example/tiendadecampeones/adapters/CartResumeAdapter.java
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/Product.java
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
  app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java
  app/src/main/res/layout/activity_cart_resume.xml
  app/src/main/res/layout/cart_resume_item.xml
Labels: documentation, enhancement, working on

#188 Subo mejoras en las activity Cart y Cart Resume
  app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java
  app/src/main/java/com/example/tiendadecampeones/adapters/CartResumeAdapter.java
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
  app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java
  app/src/main/res/layout/cart_resume_item.xml
Labels: documentation, enhancement

#189 Subo mejoras en las activity Cart, Cart Resume y PaymentMethods
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
  app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java
  app/src/main/java/com/example/tiendadecampeones/ui/PaymentMethodsActivity.java
Labels: documentation, enhancement

#190 Cristian recabarren | CartResume.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java
Labels: documentation, enhancement, help wanted

#191 Jesica alvarez- Register.java
  app/build.gradle.kts
  app/src/main/java/com/example/tiendadecampeones/models/RegisterResponse.java
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/Register.java
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: documentation, enhancement, wontfix

#192 Cristian recabarren
  app/src/main/AndroidManifest.xml
Labels: documentation, enhancement, wontfix

#194 se modifico el metodo de intent para realizar pedidos
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/PaymentMethodsActivity.java
Labels: bug

#195 Subo mejoras para las activity products, register y en apiservice
  app/src/main/java/com/example/tiendadecampeones/network/ApiService.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Register.java
Labels: documentation, enhancement

#196 Denisse sabeff - accesibilidad
  app/src/main/java/com/example/tiendadecampeones/ui/Home.java
  app/src/main/res/layout/activity_about_us.xml
  app/src/main/res/layout/activity_contacto.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement

#198 solucion de alert en home y fixes de accesibilidad
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/ui/Home.java
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
  app/src/main/res/layout/admin_orders.xml
  app/src/main/res/layout/product_card.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement

#200 actualizo ProductsAdapter y sharedpref.
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/java/com/example/tiendadecampeones/utils/SharedPrefManager.java
Labels: documentation, enhancement, wontfix

#197 Estilizacion de la card de productos: optimizados los elementos visuales
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/res/layout/product_card.xml
Labels: documentation, enhancement

#201 Cristian recabarren
  app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
  app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java
  app/src/main/java/com/example/tiendadecampeones/ui/Contact.java
  app/src/main/java/com/example/tiendadecampeones/ui/Home.java
  app/src/main/java/com/example/tiendadecampeones/ui/ManageProfile.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductCategories.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
  app/src/main/res/layout/activity_about_us.xml
  app/src/main/res/layout/activity_admin_orders.xml
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/activity_cart_resume.xml
  app/src/main/res/layout/activity_contacto.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_order.xml
  app/src/main/res/layout/activity_payment_method.xml
  app/src/main/res/layout/activity_product_categories.xml
  app/src/main/res/layout/activity_products.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/admin_orders.xml
  app/src/main/res/layout/cart_item.xml
  app/src/main/res/layout/cart_resume_item.xml
  app/src/main/res/layout/item_product_order.xml
  app/src/main/res/layout/list_item_order.xml
  app/src/main/res/layout/product_card.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement, wontfix

#202 LoginActivity.java
  app/build.gradle.kts
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
Labels: documentation, enhancement

#203 Se reparó el envío de talle y cantidad al carrito
  app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
Labels: documentation, enhancement

#205 Albano caminos
  app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
  app/src/main/java/com/example/tiendadecampeones/ui/OrderActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/PaymentMethodsActivity.java
Labels: documentation, enhancement
