Repository Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024, pull requests merged in 2024-09, with the labels that each got.

#65 Mergeo de archivos base del proyecto integrador a rama development
  .gitignore
  README.md
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/proyectointegradormobile2024/ExampleInstrumentedTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/example/proyectointegradormobile2024/ExampleUnitTest.java
  gradle/build.gradle.kts
  gradle/gradle.properties
  gradle/gradlew
  gradle/gradlew.bat
  gradle/libs.versions.toml
  gradle/settings.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: documentation, enhancement

#66 Development
  build.gradle.kts
  gradle.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: documentation, wontfix

#67 Subo las imágenes
  README.md
  app/src/main/res/assets/images/copa-del-mundo.webp
  app/src/main/res/assets/images/logo-dark.webp
  app/src/main/res/assets/images/logo-light.webp
  app/src/main/res/assets/images/not-found/404 not found.webp
  app/src/main/res/assets/images/payments/amex.webp
  app/src/main/res/assets/images/payments/mastercard.webp
  app/src/main/res/assets/images/payments/naranjax.webp
  app/src/main/res/assets/images/payments/visa.webp
  app/src/main/res/assets/images/products/Alemania/Alemania-1954-primera.webp
  app/src/main/res/assets/images/products/Alemania/Alemania-1954-segunda.webp
  app/src/main/res/assets/images/products/Alemania/Alemania-1974-primera.webp
  app/src/main/res/assets/images/products/Alemania/Alemania-1974-segunda.webp
  app/src/main/res/assets/images/products/Alemania/Alemania-2014-primera.webp
  app/src/main/res/assets/images/products/Alemania/Alemania-2014-segunda.webp
  app/src/main/res/assets/images/products/Argentina/Argentina-1978-primera.webp
  app/src/main/res/assets/images/products/Argentina/Argentina-1978-segunda.webp
  app/src/main/res/assets/images/products/Argentina/Argentina-1978-tercera.webp
  app/src/main/res/assets/images/products/Argentina/Argentina-1986-primera.webp
  app/src/main/res/assets/images/products/Argentina/Argentina-1986-segunda.webp
  app/src/main/res/assets/images/products/Argentina/Argentina-2021-Primera.webp
  app/src/main/res/assets/images/products/Background_img/Alemania.webp
  app/src/main/res/assets/images/products/Background_img/Argentina.webp
  app/src/main/res/assets/images/products/Background_img/Brasil.webp
  app/src/main/res/assets/images/products/Background_img/España.webp
  app/src/main/res/assets/images/products/Background_img/Francia.webp
  app/src/main/res/assets/images/products/Background_img/Inglaterra.webp
  app/src/main/res/assets/images/products/Background_img/Italia.webp
  app/src/main/res/assets/images/products/Background_img/Uruguay.webp
  app/src/main/res/assets/images/products/Background_img/fifa-world-cup-qatar-2022-trophy_2560x1715_xtrafondos 1.webp
  app/src/main/res/assets/images/products/Brasil/Brasil-1958-primera.webp
  app/src/main/res/assets/images/products/Brasil/Brasil-1962-primera.webp
  app/src/main/res/assets/images/products/Brasil/Brasil-1970-primera.webp
  app/src/main/res/assets/images/products/Brasil/Brasil-1970-segunda.webp
  app/src/main/res/assets/images/products/Brasil/Brasil-1994-primera.webp
  app/src/main/res/assets/images/products/Brasil/Brasil-1994-segunda.webp
  app/src/main/res/assets/images/products/Brasil/Brasil-2002-primera.webp
  app/src/main/res/assets/images/products/Brasil/Brasil-2002-segunda.webp
  app/src/main/res/assets/images/products/España/España-2010-primera.webp
  app/src/main/res/assets/images/products/España/España-2010-segunda.webp
  app/src/main/res/assets/images/products/Francia/Francia-1998-primera.webp
  app/src/main/res/assets/images/products/Francia/Francia-1998-segunda.webp
  app/src/main/res/assets/images/products/Inglaterra/Inglaterra-1966-Segunda.webp
  app/src/main/res/assets/images/products/Inglaterra/Inglaterra-1968-Primera.webp
  app/src/main/res/assets/images/products/Italia/34italia.webp
  app/src/main/res/assets/images/products/Italia/Italia-1934-Primera.webp
  app/src/main/res/assets/images/products/Italia/Italia-1938-Segunda.webp
  app/src/main/res/assets/images/products/Italia/Italia-1982-Primera.webp
  app/src/main/res/assets/images/products/Italia/Italia-1982-Segunda.webp
  app/src/main/res/assets/images/products/Italia/Italia-2006-Primera.webp
  app/src/main/res/assets/images/products/Italia/Italia-2006-Segunda.webp
  app/src/main/res/assets/images/products/Uruguay/50 uruguay.webp
  app/src/main/res/assets/images/products/Uruguay/Uruguay-1930-Primera.webp
  app/src/main/res/assets/images/products/Uruguay/Uruguay-1950-Primera.webp
  app/src/main/res/assets/images/products/gral/CAMPEONES-DE-LOS-MUNDIALES.webp
  app/src/main/res/assets/images/products/gral/argcamp.webp
  app/src/main/res/assets/images/products/gral/camisetas.webp
  app/src/main/res/assets/images/products/gral/campeones-en-octavos-1920-10.webp
  app/src/main/res/assets/images/products/gral/copa30.webp
Labels: documentation, enhancement

#74 Agrego desarrollo de actividad de productos
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
  app/src/main/res/layout/activity_products.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: documentation, enhancement

#75 subo profile
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/activity_profile.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProfileActivity.java
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/mipmap/letra_l.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: working on

#76 Denisse sabeff - About us y Contacto
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/AboutUs.java
  app/src/main/java/com/example/tiendadecampeones/Contacto.java
  app/src/main/res/layout/activity_about_us.xml
  app/src/main/res/layout/activity_contacto.xml
Labels: documentation, enhancement

#78 Agrego desarrollo de las pantallas de Login, Main, Home, Register
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/ui/Home.java
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/MainActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Register.java
  app/src/main/res/drawable/banner.jpg
  app/src/main/res/drawable/logo.jpg
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: documentation, enhancement

#79 Victoria urcola
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/style.xml
Labels: working on

#81 desarrollo de la vista payment methods
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/ui/Home.java
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/MainActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/PaymentMethodsActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Register.java
  app/src/main/res/drawable/edit_text_border.xml
  app/src/main/res/layout/activity_payment_method.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/data_extraction_rules.xml
Labels: documentation, enhancement

#82 Victoria urcola
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java
  app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_profile.xml
Labels: enhancement, working on

#83 soluciono error de tipeo en login para poder correr la app
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
Labels: enhancement

#84 Merge para arreglar conflictos en mi rama
  app/src/main/java/com/example/tiendadecampeones/Contacto.java
  app/src/main/java/com/example/tiendadecampeones/ui/AboutUsActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsCategoriesActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
  app/src/main/res/layout/activity_about_us.xml
  app/src/main/res/layout/activity_contacto.xml
  app/src/main/res/layout/activity_products.xml
  app/src/main/res/layout/product_card.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: documentation, enhancement, working on

#85 Revert "Merge para arreglar conflictos en mi rama "
  app/src/main/java/com/example/tiendadecampeones/AboutUs.java
  app/src/main/java/com/example/tiendadecampeones/Contacto.java
  app/src/main/java/com/example/tiendadecampeones/ui/CountryProducts.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
  app/src/main/res/layout/activity_about_us.xml
  app/src/main/res/layout/activity_contacto.xml
  app/src/main/res/layout/activity_products.xml
  app/src/main/res/layout/product_card.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: documentation, wontfix

#86 Denisse sabeff - Agrego Cambios en About Us y Contacto
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/AboutUs.java
  app/src/main/res/layout/activity_about_us.xml
  app/src/main/res/layout/activity_contacto.xml
  app/src/main/res/mipmap/ilustracion_copa.webp
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: documentation, enhancement

#87 Subo desarrollo de la vista Order
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/ui/Order.java
  app/src/main/res/drawable/card_background.xml
  app/src/main/res/drawable/circle_background.xml
  app/src/main/res/drawable/rounded_button_default.xml
  app/src/main/res/drawable/rounded_button_red.xml
  app/src/main/res/layout/activity_order.xml
Labels: documentation, enhancement

#88 Agrego desarrollo parcial de actividad de tarjetas de productos
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
  app/src/main/res/drawable/shopping_cart_icon_35x35.xml
  app/src/main/res/layout/activity_products.xml
  app/src/main/res/layout/product_card.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement, working on

#89 Vista resumen de compra
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java
  app/src/main/res/layout/activity_cart_resume.xml
Labels: documentation, enhancement

#90 Agrego nueva actividad con las categorías de los productos
  app/build.gradle.kts
  app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Register.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_product_categories.xml
  app/src/main/res/values/colors.xml
  gradle/libs.versions.toml
Labels: documentation, enhancement

#91 actualizo color boton finalizar sesion
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values/colors.xml
Labels: enhancement, working on

#92 agrego funcionalidad a botones que faltaban
  app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java
  app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values/colors.xml
Labels: enhancement, working on

#93 soluciono boton de finalizar sesion
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java
  app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
Labels: enhancement, working on

#94 se añadio cart y los productos
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
  app/src/main/res/drawable/add_icon_35x35.xml
  app/src/main/res/drawable/circle_button.xml
  app/src/main/res/drawable/cornershape.xml
  app/src/main/res/drawable/delete_icon_28x28.xml
  app/src/main/res/drawable/remove_icon_35x35.xml
  app/src/main/res/drawable/rounded_border_red.xml
  app/src/main/res/drawable/rounded_button2.xml
  app/src/main/res/drawable/vector_drawable.xml
  app/src/main/res/layout/activity_cart.xml
Labels: documentation, enhancement

#95 Denisse sabeff - Cambios en las activities Home, About us y contacto
  app/src/main/java/com/example/tiendadecampeones/AboutUs.java
  app/src/main/java/com/example/tiendadecampeones/Contacto.java
  app/src/main/java/com/example/tiendadecampeones/ui/Home.java
  app/src/main/res/layout/activity_about_us.xml
  app/src/main/res/layout/activity_contacto.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement

#97 actualizo Dashboard y Profile
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/MainActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java
  app/src/main/java/com/example/tiendadecampeones/ui/Home.java
  app/src/main/java/com/example/tiendadecampeones/ui/MainActivity.java
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_profile.xml
Labels: enhancement, working on

#98 dejo establecidos los redireccionamientos de Home
  app/src/main/java/com/example/tiendadecampeones/ui/Home.java
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/activity_home.xml
Labels: documentation, enhancement, working on

#99 corrijo redireccionamiento de finalizar sesion
  app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java
  app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
Labels: enhancement, working on

#102 se modificaron las imágenes y el color de la línea superior
  app/src/main/res/layout/activity_product_categories.xml
  app/src/main/res/mipmap/alemania.png
  app/src/main/res/mipmap/alemania.webp
  app/src/main/res/mipmap/argentina.png
  app/src/main/res/mipmap/argentina.webp
  app/src/main/res/mipmap/brasil.png
  app/src/main/res/mipmap/brasil.webp
  app/src/main/res/mipmap/espa_a.png
  app/src/main/res/mipmap/espa_a.webp
  app/src/main/res/mipmap/francia.png
  app/src/main/res/mipmap/francia.webp
  app/src/main/res/mipmap/inglaterra.png
  app/src/main/res/mipmap/inglaterra.webp
  app/src/main/res/mipmap/italia.png
  app/src/main/res/mipmap/italia.webp
  app/src/main/res/mipmap/uruguay.png
  app/src/main/res/mipmap/uruguay.webp
Labels: documentation, enhancement

#103 Cristian recabarren
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tiendadecampeones/AboutUs.java
  app/src/main/java/com/example/tiendadecampeones/Contacto.java
  app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java
  app/src/main/java/com/example/tiendadecampeones/adapters/CartResumeAdapter.java
  app/src/main/java/com/example/tiendadecampeones/models/Product.java
  app/src/main/java/com/example/tiendadecampeones/ui/AboutUs.java
  app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java
  app/src/main/java/com/example/tiendadecampeones/ui/Contact.java
  app/src/main/java/com/example/tiendadecampeones/ui/CountryProducts.java
  app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java
  app/src/main/java/com/example/tiendadecampeones/ui/Home.java
  app/src/main/java/com/example/tiendadecampeones/ui/PaymentMethodsActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductCategories.java
  app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java
  app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
  app/src/main/java/com/example/tiendadecampeones/ui/Register.java
  app/src/main/res/layout/activity_about_us.xml
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/activity_cart_resume.xml
  app/src/main/res/layout/activity_contacto.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_product_categories.xml
  app/src/main/res/layout/activity_products.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/cart_item.xml
  app/src/main/res/layout/cart_resume_item.xml
Labels: documentation, enhancement, working on

#104 modificacion de activity cart
  app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement
